# Generated by Django 5.2.1 on 2025-05-09 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Result Value')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
                ('result_text', models.TextField(blank=True, null=True, verbose_name='Result Text/Message')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='ФИО', max_length=255, verbose_name='Full Name')),
                ('contact_phone', models.CharField(db_column='Контактный телефон', max_length=50, verbose_name='Contact Phone')),
                ('email', models.EmailField(db_column='электронная почта', max_length=254, verbose_name='Email')),
                ('address', models.TextField(db_column='адрес', verbose_name='Address')),
                ('note', models.TextField(blank=True, db_column='примечание', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(db_column='названиеМатериала', max_length=255, verbose_name='Material Name')),
                ('color_code', models.CharField(db_column='артикулЦвета', max_length=100, verbose_name='Color Code')),
                ('cost', models.DecimalField(db_column='стоимостьЗаЕдиницу', decimal_places=2, max_digits=10, verbose_name='Cost per Unit')),
                ('note', models.TextField(blank=True, db_column='описание', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_column='названиеКомпании', max_length=255, verbose_name='Company Name')),
                ('contact_person', models.CharField(db_column='контактноеЛицо', max_length=255, verbose_name='Contact Person')),
                ('email', models.EmailField(db_column='электроннаяПочта', max_length=254, verbose_name='Email')),
                ('supplier_address', models.TextField(db_column='адресПоставщика', verbose_name='Supplier Address')),
                ('phone', models.CharField(db_column='телефон', max_length=50, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('note', models.TextField(blank=True, db_column='примечание', null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='ФИО', max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Пользовательский профиль',
                'verbose_name_plural': 'Пользовательские профили',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='ФИО', max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('hired_date', models.DateField(db_column='hiredDate', verbose_name='Hired Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Created At')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Django User')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField(db_column='описаниеДействия', verbose_name='Action Description')),
                ('action_timestamp', models.DateTimeField(auto_now_add=True, db_column='датаИВремяИзменения', verbose_name='Action Timestamp')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('employee', models.ForeignKey(blank=True, db_column='idСотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_actions', to='crm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'Записи истории',
                'ordering': ['-action_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(db_column='сумма_заказа', decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('material_quantity', models.DecimalField(db_column='количество_материала', decimal_places=3, default=0.0, max_digits=10, verbose_name='Material Quantity')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Расчет подтвержден', 'Расчет подтвержден'), ('Ожидает аванса', 'Ожидает аванса'), ('В производстве', 'В производстве'), ('Готов к установке', 'Готов к установке'), ('Ожидает установки', 'Ожидает установки'), ('Установка', 'Установка'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], db_column='статус_заказа', default='Новый', max_length=50, verbose_name='Status')),
                ('advance_payment_amount', models.DecimalField(blank=True, db_column='сумма_аванса', decimal_places=2, max_digits=12, null=True, verbose_name='Advance Payment Amount')),
                ('advance_payment_date', models.DateTimeField(blank=True, db_column='дата_внесения_аванса', null=True, verbose_name='Advance Payment Date')),
                ('installation_date', models.DateTimeField(blank=True, db_column='дата_установки', null=True, verbose_name='Installation Date')),
                ('needs_installation', models.BooleanField(db_column='установка', default=False, verbose_name='Needs Installation')),
                ('needs_delivery', models.BooleanField(db_column='доставка', default=False, verbose_name='Needs Delivery')),
                ('order_number', models.CharField(blank=True, db_column='orderNumber', max_length=50, null=True, unique=True, verbose_name='Order Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order_date', models.DateField(db_column='дата_заказа', verbose_name='Order Date')),
                ('note', models.TextField(blank=True, db_column='примечание', null=True, verbose_name='Note')),
                ('advance_payment_type', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('cashless', 'Безналичные')], max_length=50, null=True, verbose_name='Advance Payment Type')),
                ('calculation', models.ForeignKey(blank=True, db_column='id_расчета', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.calculation', verbose_name='Calculation')),
                ('client', models.ForeignKey(db_column='id_клиент', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.client', verbose_name='Client')),
                ('employee', models.ForeignKey(blank=True, db_column='id_сотрудника', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to='crm.employee', verbose_name='Responsible Employee')),
                ('material', models.ForeignKey(db_column='id_материал', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Закупленное количество')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость закупки')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безналичные')], default='cashless', max_length=20, verbose_name='Способ оплаты поставщику')),
                ('purchase_order_date', models.DateField(verbose_name='Дата заказа у поставщика')),
                ('status', models.CharField(choices=[('not-received', 'Не получен'), ('received', 'Получен'), ('cancelled', 'Отменен')], default='not-received', max_length=20, verbose_name='Статус получения')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Дата получения от поставщика')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание к закупке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='crm.material', verbose_name='Материал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_purchases', to='crm.order', verbose_name='Связанный клиентский заказ')),
            ],
            options={
                'verbose_name': 'Закупка материала',
                'verbose_name_plural': 'Закупки материалов',
                'ordering': ['-purchase_order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/attachments/', verbose_name='File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='crm.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Позиция в заказе',
                'verbose_name_plural': 'Позиции в заказе',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн-платеж'), ('credit', 'Кредит'), ('installment', 'Рассрочка')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('completed', 'Успешно завершен'), ('failed', 'Неудачный платеж'), ('refunded', 'Возврат средств'), ('partially_refunded', 'Частичный возврат')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to='crm.employee', verbose_name='Created By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='crm.supplier', verbose_name='Supplier'),
        ),
    ]
