# Generated by Django 5.2 on 2025-06-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_per_sqm',
            field=models.DecimalField(db_column='стоимостьЗаМ2', decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost per m²'),
            preserve_default=False,
        ),
    ]
