# Generated by Django 5.2 on 2025-04-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, db_column='примечание', null=True, verbose_name='Note'),
        ),
    ]
