# Generated by Django 5.2 on 2025-04-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('cashless', 'Безналичные')], max_length=50, null=True, verbose_name='Advance Payment Type'),
        ),
    ]
