# Generated by Django 5.2 on 2025-07-02 18:24

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_material_cost_per_sqm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Стоимость замера')),
                ('delivery_type', models.JSONField(default=crm.models.get_default_delivery_type, verbose_name='Стоимость доставки')),
                ('surface_bonding_per_m', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Склейка поверхностей (за м.п.)')),
                ('edge_type_per_m', models.JSONField(default=crm.models.get_default_edge_type, verbose_name='Стоимость кромки (за м.п.)')),
                ('drainage_type_per_m', models.JSONField(default=crm.models.get_default_drainage_type, verbose_name='Стоимость водоотбойника (за м.п.)')),
                ('front_bend_per_m', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Подгиб (за м.п.)')),
                ('ventilation_hole_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Вентиляционное отверстие (за шт.)')),
                ('cooktop_cutout_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Выпил под варочную панель (за шт.)')),
                ('overlay_sink_cutout_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Выпил под накладную мойку (за шт.)')),
                ('undermount_sink_installation_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Вклейка мойки подстольного монтажа (за шт.)')),
                ('on_site_joining_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Стыковка на объекте (за шт.)')),
                ('radius_10_to_300_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Сложность: радиус 10-300мм (за шт.)')),
                ('radius_300_to_1000_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Сложность: радиус 300-1000мм (за шт.)')),
                ('vertical_radius_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Сложность: вертикальный радиус (за шт.)')),
                ('two_plane_product_per_unit', models.DecimalField(decimal_places=2, default='1.00', max_digits=10, verbose_name='Сложность: изделие в 2х плоскостях (за шт.)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('last_saved', models.DateTimeField(auto_now=True, verbose_name='Last Saved')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
    ]
