# Generated by Django 5.2.1 on 2025-05-10 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_historyitem_employee_remove_order_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyitem',
            name='user',
            field=models.ForeignKey(blank=True, db_column='idUser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_actions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
