# Generated by Django 5.2 on 2025-04-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order_advance_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contactPhone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='colorCode',
            new_name='color_code',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='materialName',
            new_name='material_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contactPerson',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplierAddress',
            new_name='supplier_address',
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='crm.supplier', verbose_name='Supplier'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/attachments/', verbose_name='File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
