# Generated by Django 5.2 on 2025-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='base_multiplier',
            field=models.DecimalField(decimal_places=4, default='265.1', max_digits=10, verbose_name='Базовый множитель (было 265.1)'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='coefficient_0_300',
            field=models.DecimalField(decimal_places=4, default='1.0', max_digits=10, verbose_name='Коэф. (цена $ до 300)'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='coefficient_300_340',
            field=models.DecimalField(decimal_places=4, default='1.085', max_digits=10, verbose_name='Коэф. (цена $ 300-340)'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='coefficient_340_380',
            field=models.DecimalField(decimal_places=4, default='1.15', max_digits=10, verbose_name='Коэф. (цена $ 340-380)'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='coefficient_380_500',
            field=models.DecimalField(decimal_places=4, default='1.25', max_digits=10, verbose_name='Коэф. (цена $ 380-500)'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='coefficient_500_550',
            field=models.DecimalField(decimal_places=4, default='1.5', max_digits=10, verbose_name='Коэф. (цена $ 500-550)'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='coefficient_550_plus',
            field=models.DecimalField(decimal_places=4, default='1.6', max_digits=10, verbose_name='Коэф. (цена $ от 550)'),
        ),
    ]
