# Generated by Django 5.2 on 2025-05-02 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_contactphone_client_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (общая)')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн-платеж'), ('credit', 'Кредит'), ('installment', 'Рассрочка')], default='bank_transfer', max_length=20, verbose_name='Способ оплаты')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('ordered', 'Заказан'), ('partially_received', 'Частично получен'), ('received', 'Получен'), ('cancelled', 'Отменен'), ('returned', 'Возвращен')], default='ordered', max_length=20, verbose_name='Статус')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='crm.material', verbose_name='Материал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='crm.order', verbose_name='Заказ')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_stock_items', to='crm.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Учет материала на складе',
                'verbose_name_plural': 'Учет материалов на складе',
                'ordering': ['-order_date', 'order__order_number', 'material__material_name'],
            },
        ),
    ]
