# Generated by Django 5.2 on 2025-07-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_pricelist_base_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cost_per_sqm',
        ),
    ]
