# Generated by Django 5.2 on 2025-07-03 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_material_cost_per_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Курс доллара'),
        ),
    ]
