# Generated by Django 5.2 on 2025-05-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_purchaseorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Закупленное количество')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость закупки')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безналичные')], default='cashless', max_length=20, verbose_name='Способ оплаты поставщику')),
                ('purchase_order_date', models.DateField(verbose_name='Дата заказа у поставщика')),
                ('status', models.CharField(choices=[('not-received', 'Не получен'), ('received', 'Получен'), ('cancelled', 'Отменен')], default='not-received', max_length=20, verbose_name='Статус получения')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Дата получения от поставщика')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание к закупке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='crm.material', verbose_name='Материал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_purchases', to='crm.order', verbose_name='Связанный клиентский заказ')),
            ],
            options={
                'verbose_name': 'Закупка материала',
                'verbose_name_plural': 'Закупки материалов',
                'ordering': ['-purchase_order_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
