# Generated by Django 5.2 on 2025-07-03 12:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_calculation_dollar_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='base_multiplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('265.1'), max_digits=10, verbose_name='Базовый множитель (было 265.1)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='coefficient_0_300',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10, verbose_name='Коэф. (цена $ до 300)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='coefficient_300_340',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.085'), max_digits=10, verbose_name='Коэф. (цена $ 300-340)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='coefficient_340_380',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.15'), max_digits=10, verbose_name='Коэф. (цена $ 340-380)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='coefficient_380_500',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.25'), max_digits=10, verbose_name='Коэф. (цена $ 380-500)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='coefficient_500_550',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.5'), max_digits=10, verbose_name='Коэф. (цена $ 500-550)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='coefficient_550_plus',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.6'), max_digits=10, verbose_name='Коэф. (цена $ от 550)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='cooktop_cutout_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Выпил под варочную панель (за шт.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='front_bend_per_m',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Подгиб (за м.п.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='measurement',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Стоимость замера'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='on_site_joining_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Стыковка на объекте (за шт.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='overlay_sink_cutout_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Выпил под накладную мойку (за шт.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='radius_10_to_300_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Сложность: радиус 10-300мм (за шт.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='radius_300_to_1000_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Сложность: радиус 300-1000мм (за шт.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='surface_bonding_per_m',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Склейка поверхностей (за м.п.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='two_plane_product_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Сложность: изделие в 2х плоскостях (за шт.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='undermount_sink_installation_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Вклейка мойки подстольного монтажа (за шт.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='ventilation_hole_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Вентиляционное отверстие (за шт.)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='vertical_radius_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Сложность: вертикальный радиус (за шт.)'),
        ),
    ]
